/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToolsImport } from './routes/tools'
import { Route as SetupElectronicsImport } from './routes/setup-electronics'
import { Route as SetupImport } from './routes/setup'
import { Route as PostprocessingImport } from './routes/postprocessing'
import { Route as MaterialsImport } from './routes/materials'
import { Route as HardwareImport } from './routes/hardware'
import { Route as ElectronicsImport } from './routes/electronics'
import { Route as DesignImport } from './routes/design'
import { Route as ContributorsImport } from './routes/contributors'
import { Route as ComponentsImport } from './routes/components'
import { Route as CalculatorImport } from './routes/calculator'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ToolsRoute = ToolsImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRoute,
} as any)

const SetupElectronicsRoute = SetupElectronicsImport.update({
  id: '/setup-electronics',
  path: '/setup-electronics',
  getParentRoute: () => rootRoute,
} as any)

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const PostprocessingRoute = PostprocessingImport.update({
  id: '/postprocessing',
  path: '/postprocessing',
  getParentRoute: () => rootRoute,
} as any)

const MaterialsRoute = MaterialsImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRoute,
} as any)

const HardwareRoute = HardwareImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRoute,
} as any)

const ElectronicsRoute = ElectronicsImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => rootRoute,
} as any)

const DesignRoute = DesignImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRoute,
} as any)

const ContributorsRoute = ContributorsImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsRoute = ComponentsImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorRoute = CalculatorImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsImport
      parentRoute: typeof rootRoute
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignImport
      parentRoute: typeof rootRoute
    }
    '/electronics': {
      id: '/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof ElectronicsImport
      parentRoute: typeof rootRoute
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareImport
      parentRoute: typeof rootRoute
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsImport
      parentRoute: typeof rootRoute
    }
    '/postprocessing': {
      id: '/postprocessing'
      path: '/postprocessing'
      fullPath: '/postprocessing'
      preLoaderRoute: typeof PostprocessingImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/setup-electronics': {
      id: '/setup-electronics'
      path: '/setup-electronics'
      fullPath: '/setup-electronics'
      preLoaderRoute: typeof SetupElectronicsImport
      parentRoute: typeof rootRoute
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/components': typeof ComponentsRoute
  '/contributors': typeof ContributorsRoute
  '/design': typeof DesignRoute
  '/electronics': typeof ElectronicsRoute
  '/hardware': typeof HardwareRoute
  '/materials': typeof MaterialsRoute
  '/postprocessing': typeof PostprocessingRoute
  '/setup': typeof SetupRoute
  '/setup-electronics': typeof SetupElectronicsRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/components': typeof ComponentsRoute
  '/contributors': typeof ContributorsRoute
  '/design': typeof DesignRoute
  '/electronics': typeof ElectronicsRoute
  '/hardware': typeof HardwareRoute
  '/materials': typeof MaterialsRoute
  '/postprocessing': typeof PostprocessingRoute
  '/setup': typeof SetupRoute
  '/setup-electronics': typeof SetupElectronicsRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/components': typeof ComponentsRoute
  '/contributors': typeof ContributorsRoute
  '/design': typeof DesignRoute
  '/electronics': typeof ElectronicsRoute
  '/hardware': typeof HardwareRoute
  '/materials': typeof MaterialsRoute
  '/postprocessing': typeof PostprocessingRoute
  '/setup': typeof SetupRoute
  '/setup-electronics': typeof SetupElectronicsRoute
  '/tools': typeof ToolsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/components'
    | '/contributors'
    | '/design'
    | '/electronics'
    | '/hardware'
    | '/materials'
    | '/postprocessing'
    | '/setup'
    | '/setup-electronics'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/components'
    | '/contributors'
    | '/design'
    | '/electronics'
    | '/hardware'
    | '/materials'
    | '/postprocessing'
    | '/setup'
    | '/setup-electronics'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/components'
    | '/contributors'
    | '/design'
    | '/electronics'
    | '/hardware'
    | '/materials'
    | '/postprocessing'
    | '/setup'
    | '/setup-electronics'
    | '/tools'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ComponentsRoute: typeof ComponentsRoute
  ContributorsRoute: typeof ContributorsRoute
  DesignRoute: typeof DesignRoute
  ElectronicsRoute: typeof ElectronicsRoute
  HardwareRoute: typeof HardwareRoute
  MaterialsRoute: typeof MaterialsRoute
  PostprocessingRoute: typeof PostprocessingRoute
  SetupRoute: typeof SetupRoute
  SetupElectronicsRoute: typeof SetupElectronicsRoute
  ToolsRoute: typeof ToolsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ComponentsRoute: ComponentsRoute,
  ContributorsRoute: ContributorsRoute,
  DesignRoute: DesignRoute,
  ElectronicsRoute: ElectronicsRoute,
  HardwareRoute: HardwareRoute,
  MaterialsRoute: MaterialsRoute,
  PostprocessingRoute: PostprocessingRoute,
  SetupRoute: SetupRoute,
  SetupElectronicsRoute: SetupElectronicsRoute,
  ToolsRoute: ToolsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calculator",
        "/components",
        "/contributors",
        "/design",
        "/electronics",
        "/hardware",
        "/materials",
        "/postprocessing",
        "/setup",
        "/setup-electronics",
        "/tools"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calculator": {
      "filePath": "calculator.tsx"
    },
    "/components": {
      "filePath": "components.tsx"
    },
    "/contributors": {
      "filePath": "contributors.tsx"
    },
    "/design": {
      "filePath": "design.tsx"
    },
    "/electronics": {
      "filePath": "electronics.tsx"
    },
    "/hardware": {
      "filePath": "hardware.tsx"
    },
    "/materials": {
      "filePath": "materials.tsx"
    },
    "/postprocessing": {
      "filePath": "postprocessing.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/setup-electronics": {
      "filePath": "setup-electronics.tsx"
    },
    "/tools": {
      "filePath": "tools.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
